---
resources:
- name: bosh-musings-release-ci-docker-images
  type: git
  source:
    uri: https://github.com/myshkin5/bosh-musings-release.git
    branch: master
    paths: [ci/docker-images]

- name: bosh-musings-default-image
  type: docker-image
  source:
    repository: myshkin5/bosh-musings-default
    email: myshkin5@hub.docker.com
    username: myshkin5
    password: {{docker-password}}

- name: ubuntu
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

jobs:
- name: build-and-push
  serial: true
  plan:
  - aggregate:
    - get: bosh-musings-release-ci-docker-images
      trigger: true
      params: {submodules: none}
    - get: ubuntu
      trigger: false
  - put: bosh-musings-default-image
    params:
      load_base: ubuntu
      build: bosh-musings-release-ci-docker-images/ci/docker-images/bosh-musings-default
