---
name: bosh-musings
director_uuid: PLACEHOLDER-DIRECTOR-UUID

releases:
- {name: bosh_musings, version: latest}

networks:
- name: bosh_musings_z1
  subnets:
  - cloud_properties: {}
    range: 10.244.10.0/24
    gateway: 10.244.10.1
    static:
    - 10.244.10.2 - 10.244.10.200

resource_pools:
- name: default_z1
  network: bosh_musings_z1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

compilation:
  workers: 2
  network: bosh_musings_z1
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 15000-100000
  update_watch_time: 15000-300000

meta:
  jobs:
    web-template:
      instances: (( param "web instances must be specified" ))
      templates:
      - {name: web, release: bosh_musings}
      resource_pool: (( param "web resource pool must be specified" ))
      networks: (( param "web networks must be specified" ))

jobs:
- name: web_z1
  inject: (( inject meta.jobs.web-template ))
  instances: 1
  resource_pool: default_z1
  networks:
  - name: bosh_musings_z1
    static_ips: (( static_ips(0) ))
