---
meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

networks:
- name: default
  subnets:
  - cloud_properties: {}
    range: 10.244.10.0/24
    gateway: 10.244.10.1
    static:
    - 10.244.10.2 - 10.244.10.200

jobs:
- name: web
  instances: 1
  networks:
  - name: default
    static_ips:  (( static_ips(1) ))
