---
name: bosh-musings
director_uuid: PLACEHOLDER-DIRECTOR-UUID

releases:
- {name: bosh_musings, version: latest}

networks:
- name: bosh_musings_z1
  subnets: (( merge ))
- name: bosh_musings_z2
  subnets: (( merge ))
- name: bosh_musings_z3
  subnets: (( merge ))

resource_pools:
- name: default_z1
  network: bosh_musings_z1
  stemcell: (( grab meta.stemcell ))
- name: default_z2
  network: bosh_musings_z2
  stemcell: (( grab meta.stemcell ))
- name: default_z3
  network: bosh_musings_z3
  stemcell: (( grab meta.stemcell ))

compilation:
  workers: 2
  network: bosh_musings_z1
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 15000-100000
  update_watch_time: 15000-300000

jobs:
- name: web_z1
  instances: (( merge ))
  templates:
  - {name: web, release: bosh_musings}
  resource_pool: default_z1
  networks:
  - name: bosh_musings_z1
    static_ips: (( merge ))
- name: web_z2
  instances: (( merge ))
  templates:
  - {name: web, release: bosh_musings}
  resource_pool: default_z2
  networks:
  - name: bosh_musings_z2
    static_ips: (( merge ))
- name: web_z3
  instances: (( merge ))
  templates:
  - {name: web, release: bosh_musings}
  resource_pool: default_z3
  networks:
  - name: bosh_musings_z3
    static_ips: (( merge ))
