---
meta: (( merge ))

name: bosh-musings
director_uuid: PLACEHOLDER-DIRECTOR-UUID

releases:
- {name: bosh_musings, version: latest}

networks:
- name: default
  subnets: (( merge ))

resource_pools:
- name: default
  network: default
  stemcell: (( meta.stemcell ))

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 15000-100000
  update_watch_time: 15000-300000

jobs:
- name: web
  instances: (( merge ))
  templates:
  - {name: web, release: bosh_musings}
  resource_pool: default
  networks:
  - name: default
    static_ips: (( merge ))
