#!/usr/bin/env bash

set -e

RELEASE_DIR=$(dirname $0)/..

cd $RELEASE_DIR

git rev-parse HEAD > src/bosh-musings/version/version

$RELEASE_DIR/scripts/update-package-specs

# Will fail if the previous command changed a spec (or if the working directory is dirty)
# unless the --force option is passed to this script (which passes it on to the bosh CLI)
bosh create release $@
