#!/usr/bin/env bash

check_cmd() {
    CMD=$1
    which $CMD > /dev/null
    if [[ $? == 1 ]]; then
        help_cmd $@
    fi
    test -x $(which $CMD)
    if [[ $? == 1 ]]; then
        help_cmd $@
    fi
}

help_cmd() {
    echo "$1 not found"
    shift
    echo "Execute the following to install: $*"
    exit 1
}

check_cmd goimports "go get golang.org/x/tools/cmd/goimports"
check_cmd ginkgo    "go get github.com/onsi/ginkgo/ginkgo"

set -e

cd $(dirname $0)/../src/bosh-musings

goimports -w .

echo -e "\033[1m\033[42mUnit tests...                                                                   \033[0m"
ginkgo -r --skipPackage integration_tests --keepGoing --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress $@

echo -e "\033[1m\033[42mIntegration tests...                                                            \033[0m"
cd integration_tests
ginkgo -r --keepGoing --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress $@

echo -e "\033[1m\033[42mCompleted successfully.                                                         \033[0m"
