#!/usr/bin/env bash

check-cmd() {
    CMD=$1
    which $CMD > /dev/null
    if [[ $? == 1 ]]; then
        help-cmd $@
    fi
    test -x $(which $CMD)
    if [[ $? == 1 ]]; then
        help-cmd $@
    fi
}

help-cmd() {
    echo "$1 not found"
    shift
    echo "Execute the following to install: $*"
    exit 1
}

check-cmd goimports "go get golang.org/x/tools/cmd/goimports"
check-cmd ginkgo    "go get github.com/onsi/ginkgo/ginkgo"

set -e

error-trap() {
    echo -e "\033[1m\033[41m Failed!                                                                        \033[0m"
}

trap 'error-trap' ERR

cd $(dirname $0)/../src/bosh-musings

goimports -w .

echo -e "\033[1m\033[42m Unit tests...                                                                  \033[0m"
ginkgo -r --skipPackage endtoend_tests --keepGoing --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress $@

echo -e "\033[1m\033[42m End-to-end tests...                                                            \033[0m"
cd endtoend_tests
ginkgo -r --keepGoing --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress $@

echo -e "\033[1m\033[42m Completed successfully.                                                        \033[0m"
